# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

steps:
- task: UseDotNet@2
  inputs:
    version: '5.0.x'
    includePreviewVersions: true # Required for preview versions  
 
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test' 
    publishTestResults: true
    projects: 'tests/Items.tests' # update with your test project directory
  

